apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-prod-stage-label
  annotations:
    policies.kyverno.io/title: Require Prod Stage Label
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-stage-label-for-service
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - wealist-prod
              names:
                - "*-service"
                - "ops-portal"
      validate:
        message: "배포 실패: stage: prod 라벨이 없는 서비스 및 ops-portal은 배포할 수 없습니다."
        pattern:
          metadata:
            labels:
              stage: prod